#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-mockserver
Version  : 3.9.2
Release  : 3
URL      : https://github.com/jamesdbloom/mockserver/archive/mockserver-3.9.2.tar.gz
Source0  : https://github.com/jamesdbloom/mockserver/archive/mockserver-3.9.2.tar.gz
Source1  : https://repo1.maven.org/maven2/org/mock-server/mockserver-client-java/3.9.2/mockserver-client-java-3.9.2.jar
Source2  : https://repo1.maven.org/maven2/org/mock-server/mockserver-client-java/3.9.2/mockserver-client-java-3.9.2.pom
Source3  : https://repo1.maven.org/maven2/org/mock-server/mockserver-core/3.9.2/mockserver-core-3.9.2.jar
Source4  : https://repo1.maven.org/maven2/org/mock-server/mockserver-core/3.9.2/mockserver-core-3.9.2.pom
Source5  : https://repo1.maven.org/maven2/org/mock-server/mockserver-netty/3.9.2/mockserver-netty-3.9.2.jar
Source6  : https://repo1.maven.org/maven2/org/mock-server/mockserver-netty/3.9.2/mockserver-netty-3.9.2.pom
Source7  : https://repo1.maven.org/maven2/org/mock-server/mockserver/3.9.2/mockserver-3.9.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-mockserver-data = %{version}-%{release}

%description
MockServer
==========
**Build Status:**
[![Travis Build Status](https://travis-ci.org/jamesdbloom/mockserver.svg?branch=master)](https://travis-ci.org/jamesdbloom/mockserver)

%package data
Summary: data components for the mvn-mockserver package.
Group: Data

%description data
data components for the mvn-mockserver package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver-client-java/3.9.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver-client-java/3.9.2/mockserver-client-java-3.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver-client-java/3.9.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver-client-java/3.9.2/mockserver-client-java-3.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver-core/3.9.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver-core/3.9.2/mockserver-core-3.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver-core/3.9.2
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver-core/3.9.2/mockserver-core-3.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver-netty/3.9.2
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver-netty/3.9.2/mockserver-netty-3.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver-netty/3.9.2
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver-netty/3.9.2/mockserver-netty-3.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver/3.9.2
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/mock-server/mockserver/3.9.2/mockserver-3.9.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/mock-server/mockserver-client-java/3.9.2/mockserver-client-java-3.9.2.jar
/usr/share/java/.m2/repository/org/mock-server/mockserver-client-java/3.9.2/mockserver-client-java-3.9.2.pom
/usr/share/java/.m2/repository/org/mock-server/mockserver-core/3.9.2/mockserver-core-3.9.2.jar
/usr/share/java/.m2/repository/org/mock-server/mockserver-core/3.9.2/mockserver-core-3.9.2.pom
/usr/share/java/.m2/repository/org/mock-server/mockserver-netty/3.9.2/mockserver-netty-3.9.2.jar
/usr/share/java/.m2/repository/org/mock-server/mockserver-netty/3.9.2/mockserver-netty-3.9.2.pom
/usr/share/java/.m2/repository/org/mock-server/mockserver/3.9.2/mockserver-3.9.2.pom
